"""mis a jour champs update_at pour league

Revision ID: 10cc56cddbdd
Revises: 08b4ba072d12
Create Date: 2024-11-24 07:33:53.618728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10cc56cddbdd'
down_revision: Union[str, None] = '08b4ba072d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
