"""ajout api_usage

Revision ID: 22282d607a79
Revises: 10cc56cddbdd
Create Date: 2024-11-24 11:12:16.054697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22282d607a79'
down_revision: Union[str, None] = '10cc56cddbdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('calls_made', sa.Integer(), nullable=True),
    sa.Column('reset_time', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_usage_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_usage_id'))

    op.drop_table('api_usage')
    # ### end Alembic commands ###
