"""initial sqlite migration

Revision ID: fd8fe5c5021e
Revises: 
Create Date: 2024-11-26 06:25:03.454031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8fe5c5021e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bankroll_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initial_bankroll', sa.Float(), nullable=False),
    sa.Column('current_bankroll', sa.Float(), nullable=False),
    sa.Column('total_bets', sa.Integer(), nullable=True),
    sa.Column('winning_bets', sa.Integer(), nullable=True),
    sa.Column('losing_bets', sa.Integer(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('average_odds', sa.Float(), nullable=True),
    sa.Column('highest_bankroll', sa.Float(), nullable=False),
    sa.Column('lowest_bankroll', sa.Float(), nullable=False),
    sa.Column('longest_winning_streak', sa.Integer(), nullable=True),
    sa.Column('longest_losing_streak', sa.Integer(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('flag', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_api_id'), 'leagues', ['api_id'], unique=True)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_fixture_id', sa.Integer(), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('home_team', sa.String(length=255), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('home_team_logo', sa.String(length=255), nullable=True),
    sa.Column('away_team', sa.String(length=255), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_logo', sa.String(length=255), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('round', sa.String(length=50), nullable=True),
    sa.Column('predictions_synced', sa.Boolean(), nullable=False),
    sa.Column('last_predictions_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('odds_synced', sa.Boolean(), nullable=False),
    sa.Column('last_odds_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_api_fixture_id'), 'matches', ['api_fixture_id'], unique=True)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current', sa.Boolean(), nullable=True),
    sa.Column('has_predictions', sa.Boolean(), nullable=True),
    sa.Column('has_odds', sa.Boolean(), nullable=True),
    sa.Column('matches_synced', sa.Boolean(), nullable=False),
    sa.Column('last_match_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('h2h_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('api_fixture_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('home_team_name', sa.String(length=255), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_name', sa.String(length=255), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('halftime_home_goals', sa.Integer(), nullable=True),
    sa.Column('halftime_away_goals', sa.Integer(), nullable=True),
    sa.Column('fulltime_home_goals', sa.Integer(), nullable=True),
    sa.Column('fulltime_away_goals', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odds_bookmakers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_name', sa.String(length=100), nullable=False),
    sa.Column('bet_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('last_5_played', sa.Integer(), nullable=True),
    sa.Column('last_5_form', sa.Float(), nullable=True),
    sa.Column('last_5_att', sa.Float(), nullable=True),
    sa.Column('last_5_def', sa.Float(), nullable=True),
    sa.Column('last_5_goals_for_total', sa.Integer(), nullable=True),
    sa.Column('last_5_goals_for_average', sa.Float(), nullable=True),
    sa.Column('last_5_goals_against_total', sa.Integer(), nullable=True),
    sa.Column('last_5_goals_against_average', sa.Float(), nullable=True),
    sa.Column('league_form', sa.String(length=50), nullable=True),
    sa.Column('league_played_home', sa.Integer(), nullable=True),
    sa.Column('league_played_away', sa.Integer(), nullable=True),
    sa.Column('league_played_total', sa.Integer(), nullable=True),
    sa.Column('league_wins_home', sa.Integer(), nullable=True),
    sa.Column('league_wins_away', sa.Integer(), nullable=True),
    sa.Column('league_wins_total', sa.Integer(), nullable=True),
    sa.Column('league_draws_home', sa.Integer(), nullable=True),
    sa.Column('league_draws_away', sa.Integer(), nullable=True),
    sa.Column('league_draws_total', sa.Integer(), nullable=True),
    sa.Column('league_loses_home', sa.Integer(), nullable=True),
    sa.Column('league_loses_away', sa.Integer(), nullable=True),
    sa.Column('league_loses_total', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('winner_name', sa.String(length=255), nullable=True),
    sa.Column('winner_comment', sa.Text(), nullable=True),
    sa.Column('win_or_draw', sa.Boolean(), nullable=True),
    sa.Column('under_over', sa.String(length=20), nullable=True),
    sa.Column('goals_home', sa.String(length=20), nullable=True),
    sa.Column('goals_away', sa.String(length=20), nullable=True),
    sa.Column('advice', sa.Text(), nullable=True),
    sa.Column('percent_home', sa.Float(), nullable=True),
    sa.Column('percent_draw', sa.Float(), nullable=True),
    sa.Column('percent_away', sa.Float(), nullable=True),
    sa.Column('comparison_form_home', sa.Float(), nullable=True),
    sa.Column('comparison_form_away', sa.Float(), nullable=True),
    sa.Column('comparison_att_home', sa.Float(), nullable=True),
    sa.Column('comparison_att_away', sa.Float(), nullable=True),
    sa.Column('comparison_def_home', sa.Float(), nullable=True),
    sa.Column('comparison_def_away', sa.Float(), nullable=True),
    sa.Column('comparison_poisson_home', sa.Float(), nullable=True),
    sa.Column('comparison_poisson_away', sa.Float(), nullable=True),
    sa.Column('comparison_h2h_home', sa.Float(), nullable=True),
    sa.Column('comparison_h2h_away', sa.Float(), nullable=True),
    sa.Column('comparison_goals_home', sa.Float(), nullable=True),
    sa.Column('comparison_goals_away', sa.Float(), nullable=True),
    sa.Column('comparison_total_home', sa.Float(), nullable=True),
    sa.Column('comparison_total_away', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odds_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('odd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['odds_bookmakers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('selected_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('odds_value_id', sa.Integer(), nullable=False),
    sa.Column('bet_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['odds_value_id'], ['odds_values.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bankroll_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selected_prediction_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('bankroll_before', sa.Float(), nullable=False),
    sa.Column('bankroll_after', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['selected_prediction_id'], ['selected_predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bankroll_transactions')
    op.drop_table('selected_predictions')
    op.drop_table('odds_values')
    op.drop_table('predictions')
    op.drop_table('prediction_teams')
    op.drop_table('odds_bookmakers')
    op.drop_table('h2h_matches')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_matches_api_fixture_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_leagues_api_id'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_table('bankroll_history')
    # ### end Alembic commands ###
